name: XPBank
version: 1.1
main: net.foxsrv.xpb.XPB
api-version: 1.20
author: FoxOficial2
description: Safe store xp levels.
website: https://bank.foxsrv.net

commands:
  xpb:
    description: Comando principal do XPBank
    usage: /xpb <bal|balance|withdraw|deposit|pay|admin>
    aliases: [xpbank]

permissions:
  xpb.admin:
    description: Permite comandos administrativos
    default: op
  xpb.use:
    description: Permite usar comandos básicos
    default: true
